# Initial positions for fake hardware simulation
# Joint angles: [79.72, -69.5, -81.91, -117.92, -268.05, -157.15] degrees
shoulder_pan_joint: 1.3914
shoulder_lift_joint: -1.2132
elbow_joint: -1.4297
wrist_1_joint: -2.0584
wrist_2_joint: -4.6783
wrist_3_joint: -2.7430
2fg7_left_finger_joint: 0.0
