version: '3'

services:
  bsui:
    image: bsui:latest
    container_name: bsui
    command: ["/bin/bsui"]
  ursim:
    image: ursim:latest
    command: tail -f /dev/null
    ports:
      - 5900:5900
      - 6080:6080
    environment:
      - ROBOT_MODEL=UR5
    networks:
      ursim_net:
        ipv4_address: 10.69.26.90
    volumes:
      - ./ursim/programs:/ursim/programs

  urdriver:
    image: ur-driver:latest
    ports:
      - 50001:50001
      - 50002:50002
      - 50003:50003
      - 50004:50004
    environment:
      - ROBOT_IP=10.69.26.90
    networks:
      ursim_net:
        ipv4_address: 10.69.26.42
    depends_on:
      - ursim

  urmoveit:
    image: ur-moveit:latest
    ports:
      - 5901:5901
    environment:
      - ROBOT_IP=10.69.26.90
      - LAUNCH_RVIZ=true
    networks:
      ursim_net:
        ipv4_address: 10.69.26.43
    depends_on:
      - urdriver

  moveit-test:
    image: moveit-test:latest
    container_name: moveit-test
    privileged: true
    network_mode: host
    command: /bin/bash
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $XAUTHORITY:/root/.Xauthority
    environment:
      - ROBOT_IP=10.69.26.90
      - LAUNCH_RVIZ=true
      - QT_X11_NO_MITSHM=1
      - DISPLAY=$DISPLAY
      
    depends_on:
      - urdriver


  urexample:
    image: ur-example:latest
    environment:
      - ROBOT_IP=10.69.26.90
    networks:
      ursim_net:
        ipv4_address: 10.69.26.44
    depends_on:
      - urdriver



networks:
  ursim_net:
    ipam:
      config:
        - subnet: 10.69.26.42/24

# Can be configured to use extrernal network as well
# https://stackoverflow.com/questions/46461977/docker-compose-v3-static-ip
