cms_beamtime_server:
  ros__parameters:
    home_angles: [0.0, -1.5708, 0.00, -1.5708, 0.0, 3.14159] # Home angles for the robot
    joint_constraints:
      joint_name: 'wrist_3_joint'
      joint_position: 3.14159
      upper_limit: 0.78539
      lower_limit: 0.78539
