__version__: 27
Settings:
  Acquisitions:
    - Acquisition:
        Aperture: 4
        Brightness: 2
        ExposureTime: 30000
        Gain: 1
    - Acquisition:
        Aperture: 3.08
        Brightness: 2.5
        ExposureTime: 60000
        Gain: 1
    - Acquisition:
        Aperture: 4
        Brightness: 2
        ExposureTime: 30000
        Gain: 1
    - Acquisition:
        Aperture: 3.08
        Brightness: 2.5
        ExposureTime: 60000
        Gain: 1
  Color:
    __version__: 7
    Settings2D:
      Acquisitions:
        - Acquisition:
            Aperture: 4.36
            Brightness: 2
            ExposureTime: 20000
            Gain: 1
        - Acquisition:
            Aperture: 3.08
            Brightness: 2.5
            ExposureTime: 20000
            Gain: 1
        - Acquisition:
            Aperture: 4.36
            Brightness: 2
            ExposureTime: 20000
            Gain: 1
        - Acquisition:
            Aperture: 3.08
            Brightness: 2.5
            ExposureTime: 20000
            Gain: 1
      Processing:
        Color:
          Balance:
            Blue: 1
            Green: 1
            Red: 1
          Experimental:
            Mode: automatic
          Gamma: 1
      Sampling:
        Color: rgb
        Pixel: all
  Diagnostics:
    Enabled: no
  Engine: sage
  Processing:
    Color:
      Balance:
        Blue: __not_set__
        Green: __not_set__
        Red: __not_set__
      Experimental:
        Mode: __not_set__
      Gamma: __not_set__
    Filters:
      Cluster:
        Removal:
          Enabled: no
          MaxNeighborDistance: 10
          MinArea: 100
      Experimental:
        ContrastDistortion:
          Correction:
            Enabled: no
            Strength: 0.4
          Removal:
            Enabled: no
            Threshold: 0.5
      Hole:
        Repair:
          Enabled: no
          HoleSize: 0.2
          Strictness: 2
      Noise:
        Removal:
          Enabled: yes
          Threshold: 5
        Repair:
          Enabled: yes
        Suppression:
          Enabled: yes
      Outlier:
        Removal:
          Enabled: yes
          Threshold: 10
      Reflection:
        Removal:
          Enabled: yes
          Mode: global
      Smoothing:
        Gaussian:
          Enabled: no
          Sigma: 5
    Resampling:
      Mode: disabled
  RegionOfInterest:
    Box:
      Enabled: no
      Extents: [0, 28.7470703125]
      PointA: [173.611496, 127.998672, 364.130157]
      PointB: [-123.173767, -120.128548, 364.130157]
      PointO: [-123.173767, 127.998672, 364.130157]
    Depth:
      Enabled: no
      Range: [300, 3000]
  Sampling:
    Color: __not_set__
    Pixel: all
